### ISSUE TITLE
Fine-tuning exp

### ISSUE THREAD

**Issue by bhack** [heyoeyo/muggled_sam#2]
Thanks for this interesting refactoring. Do you plan also to experiment a fine-tuning (e.g. decoder etc..)?

The is an image and video fine-tuning exp at https://github.com/MedicineToken/Medical-SAM2 

But it is not the same interaction simulator described in the paper.

**Comment by heyoeyo** [comment]
Thanks!

> Do you plan also to experiment a fine-tuning (e.g. decoder etc..)?

I find the original v1 & v2 models already perform quite well for the examples I've tried. Similarly, the v2 video segmentation works well, even for seemingly difficult videos like this one from the [MedSAM2 demo](https://huggingface.co/spaces/junma/MedSAM2) (not sure if this is related to Medical-SAM2...?):

![med_anim](https://github.com/user-attachments/assets/8c8101f6-2515-4f01-8976-e17c072e4a61)

So at least for the foreseeable future, I don't have any plans to look into fine-tuning. More likely, I'll be adding scripts to view the internal states of models. Other fine-tuned variants can still be loaded in this repo, so those visualizations will work on them as well, which I think could be interesting.

**Comment by bhack** [comment]
Ok thanks.
