### ISSUE TITLE
GUI and Performance

### ISSUE THREAD

**Issue by Vujas-Eteph** [heyoeyo/muggled_sam#6]
Hi there👋,

Interesting project! I really appreciate that your goal is to simplify the original code by focusing on the core functionalities (easier to handle and maintain). I’m curious about the GUI you’re using—did you develop it from scratch, or is it based on an existing library?

In addition, have you tested the performance on some of the datasets (DAVIS, Y-VOS, LVOS, BURST)? Does it still maintain the same accuracy?

Cheers!

**Comment by heyoeyo** [comment]
> Interesting project!

Thanks!

> I’m curious about the GUI you’re using—did you develop it from scratch, or is it based on an existing library?

The display/mouse interaction all comes from OpenCV, which has basic GUI capabilities built-in, referred to as [HighGUI](https://docs.opencv.org/4.x/d7/dfc/group__highgui.html). The buttons/sliders etc. in this repo are all built on top of this, basically as a more elaborate form of the [paint brush demo](https://docs.opencv.org/4.x/db/d5b/tutorial_py_mouse_handling.html) on the OpenCV docs. 

The UI code is all contained in the [lib/demo_helpers/ui](https://github.com/heyoeyo/muggled_sam/tree/main/lib/demo_helpers/ui) folder, but at some point in the future I'll be splitting off as it's own repo, once I have a chance to clean it up & document it.

> In addition, have you tested the performance on some of the datasets (DAVIS, Y-VOS, LVOS, BURST)? 

No I haven't properly tested consistency on video yet. I've checked that it's 'qualitatively' similar, but I would guess it's not numerically identical to the original SAMv2 implementation. The image segmentation code is numerically identical when using identical inputs, though the pre-/post-processing steps are slightly different between muggledSAM and SAMv1/v2.

**Comment by Vujas-Eteph** [comment]
Thanks for the rapid reply! I'll check out your UI folder for inspiration. I’d also be interested in seeing it as a standalone project!

Just a side question for myself, as I'm constantly trying out new layouts/GUI options for my experiments 😅. Is there a particular motivation for using the OpenCV GUI as I’ve seen demos using Streamlit, Gradio, and even Qt. Is the OpenCV GUI more easier to maintain and to expand on compared to the aforementioned platforms?

Thanks again for clarifying the performance differences between MuggleSAM and SAM2!

**Comment by heyoeyo** [comment]
> Is there a particular motivation for using the OpenCV GUI

The main reason I like it is that it is very simple to install and use. The only thing OpenCV can really do is draw numpy arrays (representing pixel colors) as-is, so it's extremely limited but straightforward at least. It can't even (reliably) handle resizing the window or closing it without keypresses for example.

So compared to the other options you listed, I think OpenCV actually has (by far?) the worst capabilities. It's not suitable for building anything professional/user-facing. However, it is good for experimenting/prototyping/analysis type use cases. It's especially good for real-time (or near real-time) interactivity with video, which I think requires a lot more code to get working in other GUI libraries.

That being said, if you do want to try out the UI from this repo, here's a demo showing the basic usage. The general pattern is (1) define all the UI elements, (2) combine the elements into a layout, (3) repeatedly read the controls and re-render the layout in a loop (while adjusting the display based on the controls). This example opens a window with controls at the bottom for adjusting an edge detection display on a webcam (or you can change the `video_source` to point at a video file):
```python
import cv2
from lib.demo_helpers.ui.video import LoopingVideoReader, LoopingVideoPlaybackSlider
from lib.demo_helpers.ui.window import DisplayWindow
from lib.demo_helpers.ui.sliders import HSlider
from lib.demo_helpers.ui.images import ExpandingImage
from lib.demo_helpers.ui.layout import VStack, HStack

# Set up access to input video
video_source = 0  # or "/path/to/video.mp4"
vreader = LoopingVideoReader(video_source)

# Define UI elements
img_elem = ExpandingImage(vreader.get_sample_frame())
playback_slider = LoopingVideoPlaybackSlider(vreader, bar_bg_color=(90, 60, 0))
blur_slider = HSlider("Blur", 2, 0, 10, step_size=1, marker_steps=2)
low_thresh_slider = HSlider("Low threshold", 80, min_value=0, max_value=255, step_size=1)
high_thresh_slider = HSlider("High threshold", 120, min_value=0, max_value=255, step_size=1)
mix_slider = HSlider("Mix", 1, 0, 1, step_size=0.1, marker_steps=1)

# Stack elements together to form layout for display
is_webcam_source = str(video_source).isdigit()
ui_layout = VStack(
    img_elem,
    playback_slider if not is_webcam_source else None,
    blur_slider,
    HStack(low_thresh_slider, high_thresh_slider),
    mix_slider,
)

# Set up display window and pass UI events to layout object so UI can respond to mouse
window = DisplayWindow("Display - q to quit", display_fps=1000 / vreader.get_frame_delay_ms())
window.attach_mouse_callbacks(ui_layout)
window.attach_keypress_callback(" ", vreader.toggle_pause)  # Pause using spacebar

try:
    # Video loops forever!
    for is_paused, frame_idx, frame in vreader:

        # Update playback indicator, in case playing a video file
        playback_slider.update(frame_idx)

        # Read controls
        _, blur_value = blur_slider.read()
        _, low_threshold = low_thresh_slider.read()
        _, high_threshold = high_thresh_slider.read()
        _, mix_value = mix_slider.read()

        # Apply image processing to frame, based on control values
        if blur_value > 0:
            odd_blur = 1 + 2 * blur_value
            frame = cv2.blur(frame, (odd_blur, odd_blur))
        canny_frame = cv2.Canny(frame, low_threshold, high_threshold)
        canny_frame = cv2.cvtColor(canny_frame, cv2.COLOR_GRAY2BGR)
        frame = cv2.addWeighted(canny_frame, mix_value, frame, 1 - mix_value, 0)

        # Update displayed image & render full ui
        img_elem.set_image(frame)
        display_image = ui_layout.render(h=800)
        req_break, keypress = window.show(display_image)
        if req_break:
            break

finally:
    # Clean up open resources
    vreader.release()
    cv2.destroyAllWindows()
```
This is assuming the same pathing as the scripts in this repo (i.e. lib/demo_helpers/ui) but you could copy just the ui folder into another project and import from that instead. It also only needs opencv & numpy to run (using `pip install opencv-python` should be enough).

Also for future compatibility sake, this code works with [the current commit](https://github.com/heyoeyo/muggled_sam/tree/a64c23cc040773727eb0042b2f2cb363b0c2a028) of the repo as of writing, it may break in future versions.

> I’d also be interested in seeing it as a standalone project!

I'm actually trying to think of demos that could be included with the GUI code if it's on it's own repo, so if you have any questions about specific UI ideas, let me know! I might be able to make a demo out of it.

**Comment by Vujas-Eteph** [comment]
Thanks for the detailed and thoughtful insights. I might take some inspiration from your UI project for my own experiments!

In my setup, I’m currently loading images with predictions and ground truth, stacking them together (```np.hstack```), and displaying them. I use a slider and arrow key bindings to control the direction (or flow) in which I view my results. While I find that OpenCV isn't as responsive as I would like (though still better than the other alternatives), it’s something I can live with for now.

Cheers, and good luck with the rest of your work!
